In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.random.seed(21)
n_customers=500
ages=np.random.randint(17,70, size=n_customers)
genders=np.random.choice(['Male','Female'],size= n_customers)
total_spends=np.random.uniform(50, 500,size=n_customers).astype(int)
last_purchase_dates=pd.date_range(start='2023-01-05',end ='2023-06-06',periods=n_customers)
product_category_preferences=np.random.choice(['clothing','shoes','accessories'], size=n_customers)
website_visits=np.random.randint(1,30,size=n_customers)

#now creating dataframe

data=pd.DataFrame(
    {
     'customer ID': range(1,n_customers +1),
     'Age': ages,
     'Gender': genders,
     'Total Spend':total_spends,
     'Last Purchase Date':last_purchase_dates,
     'Product Category Preferences': product_category_preferences,
     'website Visits': website_visits

    }
)
data.to_csv('random_data_generator.csv',index=False)
data=pd.read_csv('random_data_generator.csv')
data

,customer ID,Age,Gender,Total Spend,Last Purchase Date,Product Category Preferences,website Visits
0,1,26,Male,88,2023-01-05 00:00:00.000000000,shoes,25
1,2,32,Female,404,2023-01-05 07:18:38.236472945,accessories,15
2,3,21,Female,243,2023-01-05 14:37:16.472945891,accessories,4
3,4,65,Male,188,2023-01-05 21:55:54.709418837,accessories,13
4,5,65,Female,467,2023-01-06 05:14:32.945891783,shoes,9
...,...,...,...,...,...,...,...
495,496,32,Male,311,2023-06-04 18:45:27.054108216,clothing,21
496,497,26,Female,335,2023-06-05 02:04:05.290581162,shoes,20
497,498,19,Female,159,2023-06-05 09:22:43.527054108,clothing,11
498,499,53,Male,481,2023-06-05 16:41:21.763527054,shoes,7
499,500,68,Female,220,2023-06-06 00:00:00.000000000,shoes,22